### ISSUE TITLE
Cannot run Docker example.

### ISSUE THREAD

**Issue by karlbateman** [gitpod-io/openvscode-server#148]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.0
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

Run ` docker run -it --init -p 3000:3000 -v "$(pwd):/home/workspace:cached" gitpod/openvscode-server:1.61.0` from the terminal and receive the following in the terminal:

```bash
[main 2021-10-10T13:13:39.477Z] rejected promise not handled within 1 second: Error: EACCES: permission denied, mkdir '/home/workspace/.openvscode-server'
[main 2021-10-10T13:13:39.482Z] stack trace: Error: EACCES: permission denied, mkdir '/home/workspace/.openvscode-server'
[main 2021-10-10T13:13:39.482Z] [Error: EACCES: permission denied, mkdir '/home/workspace/.openvscode-server'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/workspace/.openvscode-server'
}

```

**Comment by karlbateman** [comment]
Ah, running it as a regular user with the ability to interact with Docker is the cause. Running the command with `sudo` or as `root` works as expected. I'm using `Docker 20.10.9, build c2ea9bc` and have used the `dockerd-rootless-setuptool.sh install` to use Docker without root.

**Comment by josegonzalez** [comment]
I get this issue even running the docker command as the root user. It doesn't seem to matter if I run it in /tmp or the /root directory.

I'm running this on a fresh Ubuntu 20.04 instance (in Digitalocean) with all updates and Docker 20.10.16 using the `latest` tag of the opencode-server project.

**Comment by encryptblockr** [comment]
over 1 year and issue still open? anyone able to get pass this error?

**Comment by ImHereByChance** [comment]
I encountered such thing on Fedora 37. The cause is [SELinux](https://www.redhat.com/en/topics/linux/what-is-selinux) that is enabled on Fedora and RedHat distros. 
> Security-Enhanced Linux (SELinux) is a security architecture for Linux® systems that allows administrators to have more control over who can access the system. It was originally developed by the United States National Security Agency (NSA) as a series of patches to the Linux kernel using Linux Security Modules (LSM).  

It does not allow containers to write and read from mounted directories if they are not under `/usr` path on the host machine.

> When using SELinux for controlling processes within a container, you need to make sure any content that gets volume mounted into the container is readable, and potentially writable, depending on the use case.
> By default, Docker container processes run with the system_u:system_r:svirt_lxc_net_t:s0 label. The svirt_lxc_net_t type is allowed to read/execute most content under /usr, but it is not allowed to use most other types on the system.
> If you want to volume mount content under /var, for example, into a container you need to set the labels on this content. In the docker run man page we mention this.

-- [source article](https://web.archive.org/web/20190728100417/https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/)

to work around that you should run `chcon -Rt svirt_sandbox_file_t /<your_dir_path>` on the dir that you going to use as volume (on the host machine) .

**Comment by liweijian** [comment]
I got such error even I ran as `sudo` user.

I was following the [Pre-installing VSCode extensions](https://github.com/gitpod-io/openvscode-server#pre-installing-vscode-extensions) with my Dockerfile:

```
FROM gitpod/openvscode-server:latest

ENV OPENVSCODE_SERVER_ROOT="/home/.openvscode-server"
ENV OPENVSCODE="${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server"

SHELL ["/bin/bash", "-c"]
RUN \
    # Direct download links to external .vsix not available on https://open-vsx.org/
    # The two links here are just used as example, they are actually available on https://open-vsx.org/
    urls=(\
        http://192.168.86.2:8680/my-lang-0.0.11.vsix \
    )\
    # Create a tmp dir for downloading
    && tdir=/tmp/exts && mkdir -p "${tdir}" && cd "${tdir}" \
    # Download via wget from $urls array.
    && wget "${urls[@]}" && \
    # List the extensions in this array
    exts=(\
        # From https://open-vsx.org/ registry directly
        gitpod.gitpod-theme \
        # From filesystem, .vsix that we downloaded (using bash wildcard '*')
        "${tdir}"/* \
    )\
    # Install the $exts
    && for ext in "${exts[@]}"; do ${OPENVSCODE} --install-extension "${ext}"; done
```

Built it with: `sudo docker build -t openvscode .` , with the result:

```sh
$ sudo docker images
REPOSITORY         TAG       IMAGE ID       CREATED          SIZE
openvscode         latest    b376dc586f9b   40 seconds ago   506MB
```

And got that error when:

```sh
$ sudo docker run -it --init -p 3000:3000 -v "$(pwd):/home/workspace:cached" openvscode
Server bound to 0.0.0.0:3000 (IPv4)
Extension host agent listening on 3000

Error: EACCES: permission denied, mkdir '/home/workspace/.openvscode-server'
    at Object.mkdirSync (node:fs:1336:3)
    at /home/.openvscode-server/out/vs/server/node/server.main.js:188:1770
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/.openvscode-server/out/vs/server/node/server.main.js:188:1735)
    at Function._safeInvokeFunction (/home/.openvscode-server/out/server-main.js:3:1245)
    at Function._invokeFactory (/home/.openvscode-server/out/server-main.js:3:1425)
    at v.complete (/home/.openvscode-server/out/server-main.js:3:1682)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1051)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1297)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1297)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1297)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1297)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1297)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1297)
    at d._resolve (/home/.openvscode-server/out/server-main.js:4:510)
    at defineModule (/home/.openvscode-server/out/server-main.js:3:5524)
    at r (/home/.openvscode-server/out/server-main.js:3:9566)
    at Object.S (/home/.openvscode-server/out/server-main.js:4:5901)
    at Function._safeInvokeFunction (/home/.openvscode-server/out/server-main.js:3:1245)
    at Function._invokeFactory (/home/.openvscode-server/out/server-main.js:3:1425)
    at v.complete (/home/.openvscode-server/out/server-main.js:3:1682)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1051)
    at d._onModuleComplete (/home/.openvscode-server/out/server-main.js:4:1297)
    at d._resolve (/home/.openvscode-server/out/server-main.js:4:510)
    at defineModule (/home/.openvscode-server/out/server-main.js:3:5524)
    at g (/home/.openvscode-server/out/server-main.js:4:1741)
    at P (/home/.openvscode-server/out/server-main.js:2:2455)
    at Object.<anonymous> (/home/.openvscode-server/out/vs/server/node/server.main.nls.js:3:61)
    at n._createAndEvalScript (/home/.openvscode-server/out/server-main.js:2:2499)
    at /home/.openvscode-server/out/server-main.js:2:2140
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/workspace/.openvscode-server'
}
```

**Comment by pliniozanini** [comment]
Having the same issue running on a clean Ubuntu 22.04 instance in Oracle Cloud. 
Running with sudo or adding user to docker group did not change a thing in the output.

**Comment by nt202** [comment]
Here is what worked:
mkdir data
sudo chmod 777 ./data

```
version: "2.1"
services:
  code-server:
    image: gitpod/openvscode-server
    container_name: openvscode_container
    volumes:
      - ./data:/home/workspace:cached
    ports:
      - 3000:3000
    restart: unless-stopped
```

docker compose up -d

**Comment by Repeater9** [comment]
When I bind mount my working directory (i.e. `$pwd`) to `/home/workspace` inside the container, the `uid` and `gid` of `/home/workspace` is the same with `$pwd` in my host.

However, both uid and gid of `/home/workspace` inside the container is expected to be `1000` (specified in [Dockerfile](https://github.com/gitpod-io/openvscode-releases/blob/main/Dockerfile)).

I remove the `-v` option in `docker run`, and it works.
