### ISSUE TITLE
Server won't start properly on arm64 platform

### ISSUE THREAD

**Issue by PaganMuffin** [gitpod-io/openvscode-server#239]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

 1. wget https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.62.2/openvscode-server-v1.62.2-linux-arm64.tar.gz
  2. tar -zxf openvscode-server-v1.62.2-linux-arm64.tar.gz
  3. cd openvscode-server-v1.62.2-linux-arm64
  4.  ./server.sh
 
I'm trying to run it on Oracle Cloud ARM Instance (4 core, 24GB ram), but aftar step 4 it start showing errors in console.

```
Extension host agent listening on 8000

Web UI available at http://localhost:8000/?tkn=bcb67e46-80f7-4ed6-8c05-c9643d97c257
[21:02:57] Extension host agent started.
Error: /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:101)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:4:1723)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10695)
    at d (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10300)
    at Object.errorback (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10421)
    at e.triggerErrorback (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:11059)
    at /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10765
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:4:1740)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10695)
    at d (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10300)
    at i._loadModule (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10430)
    at i._resolve (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:6:452)
    at i.defineModule (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:6142)
    at i._relativeRequire (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:6828)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:9406)
    at v (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostAgent.js:88:37741)
    at new Promise (<anonymous>)
    at p (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostAgent.js:88:37721)
    at k._createSpdLogLogger (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostAgent.js:88:38701)
    at new k (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostAgent.js:88:38517)
    at /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostAgent.js:181:126
    at new Te (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostAgent.js:145:130719)
    at Ve (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostAgent.js:165:337)
    at Object.n [as createServer] (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostAgent.js:181:1378)
    at /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/main.js:1:823
    at async Server.<anonymous> (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/main.js:8:99) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[21:03:07] [Error: ENOENT: no such file or directory, scandir '/home/ubuntu/.vscode-remote/data/logs'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/ubuntu/.vscode-remote/data/logs'
```
I can't open VSCode in browser but, when I'm trying to open terminal it show in browser:

```
The terminal process failed to launch: A native exception occurred during launch (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/build/Release/pty.node: cannot open shared object file: No such file or directory).
```

and this in console:

```[IPC Library: Pty Host] innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/lib/unixTerminal.js
- /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/lib/index.js
- /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/bootstrap-amd.js
- /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/lib/index.js:14:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:101)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:4:1723)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10695)
    at d (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10300)
    at i._loadModule (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10430)
    at i._resolve (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:6:452)
    at i.defineModule (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:6142)
    at i._relativeRequire (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:6828)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:9406)
    at /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/platform/terminal/node/ptyHostMain.js:14:42494
    at new Promise (<anonymous>)
    at Se.setupPtyProcess (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/platform/terminal/node/ptyHostMain.js:14:42474)
    at async Se.start (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/platform/terminal/node/ptyHostMain.js:14:41234)
    at async start (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/platform/terminal/node/ptyHostMain.js:17:10037)
[IPC Library: Pty Host] innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/lib/unixTerminal.js
- /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/lib/index.js
- /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/bootstrap-amd.js
- /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/node-pty/lib/index.js:14:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:101)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:4:1723)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10695)
    at d (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10300)
    at Object.errorback (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10421)
    at e.triggerErrorback (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:11059)
    at /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10765
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:4:1740)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10695)
    at d (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10300)
    at i._loadModule (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10430)
    at i._resolve (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:6:452)
    at i.defineModule (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:6142)
    at i._relativeRequire (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:6828)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:9406)
    at /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/platform/terminal/node/ptyHostMain.js:14:42494
    at new Promise (<anonymous>)
    at Se.setupPtyProcess (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/platform/terminal/node/ptyHostMain.js:14:42474)
    at async Se.start (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/platform/terminal/node/ptyHostMain.js:14:41234)
    at async start (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/platform/terminal/node/ptyHostMain.js:17:10037)
[21:07:56] [::ffff:127.0.0.1][577d88ab][ExtensionHostConnection] New connection established.
[21:07:56] [::ffff:127.0.0.1][577d88ab][ExtensionHostConnection] <18893> Launched Extension Host Process.
[21:07:56] [::ffff:127.0.0.1][577d88ab][ExtensionHostConnection] <18893> Error: /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.n._load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:113:28606)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.n._load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:113:28606)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:101)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:4:1723)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10695)
    at d (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10300)
    at Object.errorback (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10421)
    at e.triggerErrorback (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:11059)
    at /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10765
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:4:1740)
    at e.load (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:3:10695)
    at d (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10300)
    at i._loadModule (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:10430)
    at i._resolve (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:6:452)
    at i.defineModule (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:6142)
    at i._relativeRequire (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:6828)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/loader.js:5:9406)
    at l (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:84:7603)
    at new Promise (<anonymous>)
    at y (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:84:7583)
    at D._createSpdLogLogger (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:84:8563)
    at new D (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:84:8379)
    at new D (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:94:89407)
    at i._createInstance (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:82:1374)
    at i._createServiceInstance (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:82:3775)
    at i._createServiceInstanceWithOwner (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:82:3291)
    at i._createAndCacheServiceInstance (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:82:2966)
    at i._safeCreateAndCacheServiceInstance (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:82:2164)
    at i._getOrCreateServiceInstance (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:82:1885)
    at Object.get (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:82:453)
    at /home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:102:10055
    at invokeFunction (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:82:319)
    at new b (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:102:10035)
    at r (/home/ubuntu/vscode-server/openvscode-server-v1.62.2-linux-arm64/out/vs/server/remoteExtensionHostProcess.js:113:32632)```

**Comment by SBell6hf** [comment]
![BA7C6162-453E-432D-B650-931978C7920A](https://user-images.githubusercontent.com/94227866/142630444-af02498c-4384-4736-bb40-12819f67fde3.jpeg)
It seems all local bindings are compiled for x86_64.

**Comment by TreeHD** [comment]
same issue
missing spdlog on ARM64

**Comment by jeanp413** [comment]
Hi @PaganMuffin @SBell6hf @TreeHD, thanks for trying the arm builds and reporting this issue.
I've updated the github insiders release and the docker insiders images, also a new stable release `1.62.3` will be out in a few minutes. Could you give another try and let me know if they are working this time?
Thanks.

**Comment by TreeHD** [comment]
> Hi @PaganMuffin @SBell6hf @TreeHD, thanks for trying the arm builds and reporting this issue.
> I've updated the github insiders release and the docker insiders images. Could you give another try and let me know if it's working this time?
> Thanks.

Seems it's working.
Thanks!!

![IMG_20211121_093356.jpg](https://user-images.githubusercontent.com/23317010/142745872-ae888865-dc7c-4188-8522-805a6952649a.jpg)

**Comment by jeanp413** [comment]
Great to hear it's working :tada:
