### ISSUE TITLE
Kogito Breaks IDE

### ISSUE THREAD

**Issue by ccravens** [gitpod-io/openvscode-server#251]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
![image](https://user-images.githubusercontent.com/1319049/144344637-52cd4b7f-6f85-42d6-bcb6-d7a2e42f0ffc.png)

- OS Version:
![image](https://user-images.githubusercontent.com/1319049/144344689-a19e0f7f-0c1f-4da1-9934-25545dc5187e.png)

Steps to Reproduce:

1. Install Kogito Extension (search Kogito, install)
2. Create test file test.bpmn, the editor stays spinning forever:
![image](https://user-images.githubusercontent.com/1319049/144344774-ebc6f607-ee73-4e84-9134-c44cb970585b.png)

3. Interact with the DMN editor and the whole application crashes:
![image](https://user-images.githubusercontent.com/1319049/144344899-cba9ebc4-bd9b-48e2-b363-ef9c1d71179a.png)

![image](https://user-images.githubusercontent.com/1319049/144344962-d58d8ca1-31e5-4c0e-bb99-76e500ce8f82.png)

Seeing this in the logs:
```
[02:08:22] [File Watcher (parcel)] Unexpected error: Operation not permitted (EUNKNOWN) (path: /home/workspace)
[02:08:22] [File Watcher (parcel)] restarting watcher after error: Operation not permitted
[02:08:22] [File Watcher (parcel)] Unexpected error: Operation not permitted (EUNKNOWN) (path: /home/workspace)
[02:08:22] [File Watcher (parcel)] restarting watcher after error: Operation not permitted
[02:08:23] [File Watcher (parcel)] Unexpected error: Operation not permitted (EUNKNOWN) (path: /home/workspace)
[02:08:23] [File Watcher (parcel)] restarting watcher after error: Operation not permitted
[02:08:23] [File Watcher (parcel)] Unexpected error: Operation not permitted (EUNKNOWN) (path: /home/workspace)
[02:08:23] [File Watcher (parcel)] restarting watcher after error: Operation not permitted
[02:08:24] [File Watcher (parcel)] Unexpected error: Operation not permitted (EUNKNOWN) (path: /home/workspace)
[02:08:24] [File Watcher (parcel)] restarting watcher after error: Operation not permitted
[02:08:25] [File Watcher (parcel)] Unexpected error: Operation not permitted (EUNKNOWN) (path: /home/workspace)
[02:08:25] [File Watcher (parcel)] gave up attempting to restart watcher after error: Operation not permitted
```

and lots of this before installing Kogito extension:
```
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/openvscode-server-v1.62.3/out/bootstrap.js:1:370)
    at process.emit (events.js:315:20)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/openvscode-server-v1.62.3/out/bootstrap.js:1:370)
    at process.emit (events.js:315:20)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/openvscode-server-v1.62.3/out/bootstrap.js:1:370)
    at process.emit (events.js:315:20)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/openvscode-server-v1.62.3/out/bootstrap.js:1:370)
    at process.emit (events.js:315:20)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/openvscode-server-v1.62.3/out/bootstrap.js:1:370)
    at process.emit (events.js:315:20)
```

**Comment by akosyakov** [comment]
Please reach out to the extension author.

**Comment by jeanp413** [comment]
@ccravens  I just tested this on Ubuntu linux and it works fine. Maybe it's related to this https://github.com/gitpod-io/openvscode-server/issues/148? Are you running docker with sudo?
