### ISSUE TITLE
Connection error: Client refused: version mismatch

### ISSUE THREAD

**Issue by NovaLogicDev** [gitpod-io/openvscode-server#529]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: [1.81.1](https://hub.docker.com/layers/gitpod/openvscode-server/1.81.1/images/sha256-d329f3a0fa117cd0e44283f5f72b37db071658169df951a3467221c90b96bb87?context=explore)
- OS Version: Official Docker Image

Steps to Reproduce:

1. Deploy Container
2. Navigate to localhost:3000
3. Receive the following popup
![image](https://github.com/gitpod-io/openvscode-server/assets/39929570/792cc3c2-a4e5-4b77-b2f5-fd505c307fc8)
5. Press Reload
6. Same Popup

Logs:
```
 INFO Resolving connection token (editor.novalogic.dev)...
workbench.web.main.js:624  INFO Resolved connection token (editor.novalogic.dev) after 2 ms
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-af1b1916-6164-4f9a-8ebe-c387bebbd28d)...
workbench.web.main.js:1157  An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ workbench.web.main.js:1157
fc @ workbench.web.main.js:2541
gc @ workbench.web.main.js:2541
tc @ workbench.web.main.js:2541
jc @ workbench.web.main.js:2541
setInput @ workbench.web.main.js:2541
await in setInput (async)
M @ workbench.web.main.js:2312
D @ workbench.web.main.js:2312
openEditor @ workbench.web.main.js:2312
(anonymous) @ workbench.web.main.js:2492
xb @ workbench.web.main.js:2492
hb @ workbench.web.main.js:2492
mn @ workbench.web.main.js:2492
j @ workbench.web.main.js:619
createInstance @ workbench.web.main.js:619
createFromSerialized @ workbench.web.main.js:2492
Cb @ workbench.web.main.js:2492
fromJSON @ workbench.web.main.js:2492
o @ workbench.web.main.js:204
(anonymous) @ workbench.web.main.js:204
o @ workbench.web.main.js:204
n @ workbench.web.main.js:204
deserialize @ workbench.web.main.js:204
deserialize @ workbench.web.main.js:204
Qb @ workbench.web.main.js:2492
Pb @ workbench.web.main.js:2492
Ob @ workbench.web.main.js:2492
I @ workbench.web.main.js:2492
create @ workbench.web.main.js:759
dc @ workbench.web.main.js:2522
(anonymous) @ workbench.web.main.js:2522
invokeFunction @ workbench.web.main.js:619
startup @ workbench.web.main.js:2522
open @ workbench.web.main.js:2541
await in open (async)
d @ workbench.web.main.js:2541
(anonymous) @ workbench.js:3
(anonymous) @ workbench.js:3
_invokeFactory @ loader.js:5
complete @ loader.js:5
_onModuleComplete @ loader.js:6
_resolve @ loader.js:6
defineModule @ loader.js:5
y @ loader.js:6
(anonymous) @ workbench.js:3
(anonymous) @ workbench.js:3
workbench.web.main.js:1530  The web worker extension host is started in a same-origin iframe!
u @ workbench.web.main.js:1530
v @ workbench.web.main.js:1530
start @ workbench.web.main.js:1530
Jr @ workbench.web.main.js:1553
j @ workbench.web.main.js:619
createInstance @ workbench.web.main.js:619
f @ workbench.web.main.js:1553
tb @ workbench.web.main.js:2628
sb @ workbench.web.main.js:2628
rb @ workbench.web.main.js:2628
gb @ workbench.web.main.js:2627
(anonymous) @ workbench.web.main.js:2628
Promise.then (async)
A @ workbench.web.main.js:2628
j @ workbench.web.main.js:619
t @ workbench.web.main.js:619
s @ workbench.web.main.js:619
r @ workbench.web.main.js:619
q @ workbench.web.main.js:619
m @ workbench.web.main.js:619
get @ workbench.web.main.js:619
db @ workbench.web.main.js:2522
(anonymous) @ workbench.web.main.js:2522
invokeFunction @ workbench.web.main.js:619
startup @ workbench.web.main.js:2522
open @ workbench.web.main.js:2541
await in open (async)
d @ workbench.web.main.js:2541
(anonymous) @ workbench.js:3
(anonymous) @ workbench.js:3
_invokeFactory @ loader.js:5
complete @ loader.js:5
_onModuleComplete @ loader.js:6
_resolve @ loader.js:6
defineModule @ loader.js:5
y @ loader.js:6
(anonymous) @ workbench.js:3
(anonymous) @ workbench.js:3
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-2dddcc27-a2dd-49b3-96a8-b71b5c83c90a)...
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-af1b1916-6164-4f9a-8ebe-c387bebbd28d) was successful after 254 ms.
loader.js:3 
        
        
        GET https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vsda.js net::ERR_ABORTED 404 (Not Found)
load @ loader.js:3
load @ loader.js:3
u @ loader.js:5
_loadModule @ loader.js:5
_resolve @ loader.js:6
defineModule @ loader.js:5
_relativeRequire @ loader.js:5
e @ loader.js:5
(anonymous) @ workbench.web.main.js:657
j @ workbench.web.main.js:657
E.S.<computed> @ workbench.web.main.js:6
c @ workbench.web.main.js:657
createNewMessage @ workbench.web.main.js:657
f @ workbench.web.main.js:654
await in f (async)
b @ workbench.web.main.js:654
m @ workbench.web.main.js:654
(anonymous) @ workbench.web.main.js:654
D @ workbench.web.main.js:654
await in D (async)
T @ workbench.web.main.js:654
p @ workbench.web.main.js:2309
n @ workbench.web.main.js:2309
getChannel @ workbench.web.main.js:2309
withChannel @ workbench.web.main.js:2309
j @ workbench.web.main.js:2309
getRawEnvironment @ workbench.web.main.js:2309
(anonymous) @ workbench.web.main.js:1851
register @ workbench.web.main.js:1851
i @ workbench.web.main.js:2541
await in i (async)
open @ workbench.web.main.js:2541
d @ workbench.web.main.js:2541
(anonymous) @ workbench.js:3
(anonymous) @ workbench.js:3
_invokeFactory @ loader.js:5
complete @ loader.js:5
_onModuleComplete @ loader.js:6
_resolve @ loader.js:6
defineModule @ loader.js:5
y @ loader.js:6
(anonymous) @ workbench.js:3
(anonymous) @ workbench.js:3
editor.novalogic.dev/:1  Refused to execute script from 'https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vsda.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=3d6312b4-3d21-458e-a16a-f82cb39eec9b:1  An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
workbench.web.main.js:658 
        
        
        GET https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vsda_bg.wasm 404 (Not Found)
k @ workbench.web.main.js:658
j @ workbench.web.main.js:657
E.S.<computed> @ workbench.web.main.js:6
c @ workbench.web.main.js:657
createNewMessage @ workbench.web.main.js:657
f @ workbench.web.main.js:654
await in f (async)
b @ workbench.web.main.js:654
m @ workbench.web.main.js:654
(anonymous) @ workbench.web.main.js:654
D @ workbench.web.main.js:654
await in D (async)
T @ workbench.web.main.js:654
p @ workbench.web.main.js:2309
n @ workbench.web.main.js:2309
getChannel @ workbench.web.main.js:2309
withChannel @ workbench.web.main.js:2309
j @ workbench.web.main.js:2309
getRawEnvironment @ workbench.web.main.js:2309
(anonymous) @ workbench.web.main.js:1851
register @ workbench.web.main.js:1851
i @ workbench.web.main.js:2541
await in i (async)
open @ workbench.web.main.js:2541
d @ workbench.web.main.js:2541
(anonymous) @ workbench.js:3
(anonymous) @ workbench.js:3
_invokeFactory @ loader.js:5
complete @ loader.js:5
_onModuleComplete @ loader.js:6
_resolve @ loader.js:6
defineModule @ loader.js:5
y @ loader.js:6
(anonymous) @ workbench.js:3
(anonymous) @ workbench.js:3
workbench.web.main.js:624   ERR [remote-connection][Management   ][af1b1…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-fb093b78-6f64-42ef-b0e1-25da279b6d50)...
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-2dddcc27-a2dd-49b3-96a8-b71b5c83c90a) was successful after 365 ms.
workbench.web.main.js:624   ERR [remote-connection][ExtensionHost][2dddc…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-8cf9c0c2-a4d2-4311-97bf-db131c552a50)...
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-fb093b78-6f64-42ef-b0e1-25da279b6d50) was successful after 287 ms.
workbench.web.main.js:624   ERR [remote-connection][Management   ][fb093…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-ff2e252e-4693-4f3f-80d5-45d115622475)...
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-8cf9c0c2-a4d2-4311-97bf-db131c552a50) was successful after 355 ms.
workbench.web.main.js:624   ERR [remote-connection][ExtensionHost][8cf9c…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-a4f31d88-418a-472b-aae2-6aaf7295c89f)...
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-ff2e252e-4693-4f3f-80d5-45d115622475) was successful after 435 ms.
workbench.web.main.js:624   ERR [remote-connection][Management   ][ff2e2…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 3] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-92692362-0484-43b0-ac23-e1939cb7fc7c)...
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-a4f31d88-418a-472b-aae2-6aaf7295c89f) was successful after 403 ms.
workbench.web.main.js:624   ERR [remote-connection][ExtensionHost][a4f31…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 3] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-44cbd5a2-19e8-4e67-93b4-7665acd6b65a)...
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-92692362-0484-43b0-ac23-e1939cb7fc7c) was successful after 416 ms.
workbench.web.main.js:624   ERR [remote-connection][Management   ][92692…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 4] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-ce46ea83-b269-40b6-be0e-48a07cb3f476)...
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-44cbd5a2-19e8-4e67-93b4-7665acd6b65a) was successful after 454 ms.
workbench.web.main.js:624   ERR [remote-connection][ExtensionHost][44cbd…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 4] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-871ae03a-08be-4f47-a12c-ad705fc8b3b9)...
workbench.web.main.js:624  INFO Creating a socket (renderer-Management-ce46ea83-b269-40b6-be0e-48a07cb3f476) was successful after 519 ms.
workbench.web.main.js:624  INFO Updating additional builtin extensions cache
workbench.web.main.js:624   ERR [remote-connection][Management   ][ce46e…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 5]  An error occurred in initial connection! It will be treated as a permanent error. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR Cannot register remote filesystem provider. Error while fetching remote environment. Connection error: Client refused: version mismatch
4workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR Connection error: Client refused: version mismatch: Error: Connection error: Client refused: version mismatch
    at U (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:654:23877)
    at o.value (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:654:15550)
    at c.w (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:69:1902)
    at c.fire (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:69:2119)
    at r.fire (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:593:13708)
    at b.z (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:593:16807)
    at o.value (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:593:15225)
    at c.w (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:69:1902)
    at c.fire (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:69:2119)
    at o.acceptChunk (https://editor.novalogic.dev/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:593:11482)
workbench.web.main.js:1992  Activating extension 'vscode.git-base' failed: Error.
$onExtensionActivationError @ workbench.web.main.js:1992
N @ workbench.web.main.js:1553
M @ workbench.web.main.js:1553
H @ workbench.web.main.js:1553
G @ workbench.web.main.js:1553
(anonymous) @ workbench.web.main.js:1553
w @ workbench.web.main.js:69
fire @ workbench.web.main.js:69
N.onmessage @ workbench.web.main.js:1530
workbench.web.main.js:1992  Activating extension 'vscode.merge-conflict' failed: Error.
$onExtensionActivationError @ workbench.web.main.js:1992
N @ workbench.web.main.js:1553
M @ workbench.web.main.js:1553
H @ workbench.web.main.js:1553
G @ workbench.web.main.js:1553
(anonymous) @ workbench.web.main.js:1553
w @ workbench.web.main.js:69
fire @ workbench.web.main.js:69
N.onmessage @ workbench.web.main.js:1530
workbench.web.main.js:624  INFO Creating a socket (renderer-ExtensionHost-871ae03a-08be-4f47-a12c-ad705fc8b3b9) was successful after 596 ms.
workbench.web.main.js:624   ERR [remote-connection][ExtensionHost][871ae…][initial][WebSocket(editor.novalogic.dev:443)] received error control message when negotiating connection. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR [remote-connection][attempt 5]  An error occurred in initial connection! It will be treated as a permanent error. Error:
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
workbench.web.main.js:624   ERR Error received from starting extension host (kind: Remote)
workbench.web.main.js:624   ERR Error: Connection error: Client refused: version mismatch
    at U (workbench.web.main.js:654:23877)
    at o.value (workbench.web.main.js:654:15550)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at r.fire (workbench.web.main.js:593:13708)
    at b.z (workbench.web.main.js:593:16807)
    at o.value (workbench.web.main.js:593:15225)
    at c.w (workbench.web.main.js:69:1902)
    at c.fire (workbench.web.main.js:69:2119)
    at o.acceptChunk (workbench.web.main.js:593:11482)
```

**Comment by NovaLogicDev** [comment]
this error was solved by updating the product.json.
